# tasks file for ansible-role-container-registry

- name: ensure docker-distribution is installed
  yum:
    name: docker-distribution
    state: present

- name: manage /etc/docker-distribution/registry/config.yml
  template:
    src: docker-distribution-config.yml.j2
    dest: /etc/docker-distribution/registry/config.yml
  notify: restart docker-distribution service

- name: enable and start docker-distribution
  systemd:
    enabled: true
    state: started
    name: docker-distribution

- name: validate that registry is up
  uri:
    # Just checking API version should be fine
    # https://docs.docker.com/registry/spec/api/#api-version-check
    url: "http://{{ container_registry_host }}:{{ container_registry_port }}/v2/"
