# tasks file for ansible-role-container-registry

- name: ensure docker-distribution is installed
  package:
    name: docker-distribution
    state: present
  become: true

- name: manage /etc/docker-distribution/registry/config.yml
  template:
    src: docker-distribution-config.yml.j2
    dest: /etc/docker-distribution/registry/config.yml
  become: true
  notify: restart docker-distribution service

- name: force systemd to reread configs
  meta: flush_handlers

- name: enable and start docker-distribution
  systemd:
    enabled: true
    state: started
    name: docker-distribution
  become: true
