# tasks file for ansible-role-container-registry

- name: ensure docker-distribution is installed
  yum:
    name: docker-distribution
    state: present

- name: install the latest version of openstack-kolla
  yum:
    name: openstack-kolla
    state: latest
  when: container_registry_enable_container_images_build|bool

- name: manage /etc/docker-distribution/registry/config.yml
  template:
    src: docker-distribution-config.yml.j2
    dest: /etc/docker-distribution/registry/config.yml
  notify: restart docker-distribution service

- name: enable and start docker-distribution
  systemd:
    enabled: true
    state: started
    name: docker-distribution
